[package]
name = "coo"
version = "0.1.0"
authors = ["Motoki Naruse <motoki@naru.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
